window.GARDINER_DATA=[
  ['A1','𓀀','.j|z','seated man'],
  ['A2','𓀁','wnm|zwr|sḏd|gr|kꜣj|mrj','man with hand to mouth'],
  ['A3','𓀂','ḥmsj','man sitting on heel'],
  ['A4','𓀃','dwꜣ|jmn','seated man with hands raised'],
  ['A5','𓀄','jmn','crouching man hiding behind wall'],
  ['A6','𓀆','wꜤb','seated man under vase from which water flows'],
  ['A7','𓀉','wrḏ','fatigued man'],
  ['A8','𓀊','hnw','man performing hnw-rite'],
  ['A9','𓀋','kꜣt|ꜣdp|fꜣj','man steadying basket on head'],
  ['A10','𓀌','sqdw|ẖn','seated man holding oar'],
  ['A11','𓀍','ḫnms','seated man holding scepter of authority and shepherd\'s crook'],
  ['A12','𓀎','mnfyt|mšꜥ','soldier with bow and quiver'],
  ['A13','𓀏','ḫfty|sbj','man with arms tied behind his back'],
  ['A14','𓀐','mwt|ḫfty','falling man with blood streaming from his head'],
  ['A15','𓀒','ḫr','man falling'],
  ['A16','𓀓','ksj','man bowing down'],
  ['A17','𓀔','ms|nn (šrj|nmḥ|ẖrd|ḫy|nnj)','child sitting with hand to mouth'],
  ['A18','𓀖','jmty','child wearing red crown'],
  ['A19','𓀗','jk (jꜣw|smsw|wr|rhn|ḥwj)','bent man leaning on staff'],
  ['A20','𓀘','smsw','man leaning on forked staff'],
  ['A21','𓀙','sr|smr|wr|ḥwj','man holding staff with handkerchief'],
  ['A22','𓀚','ḥnṯ|twt','statue of man with staff and scepter of authority'],
  ['A23','𓀛','jty','king with staff and mace with round head'],
  ['A24','𓀜','ḥwj|nḫt|sbꜣ|njs|ḥꜥj','man striking with both hands'],
  ['A25','𓀝','ḥwj','man striking, with left arm hanging behind back'],
  ['A26','𓀞','njs|Ꜥš','man with one arm pointing forward'],
  ['A27','𓀟','jnj','hastening man'],
  ['A28','𓀠','qꜣj|ḥꜣj','man with hands raised on either side'],
  ['A29','𓀡','sḫd','man upside down'],
  ['A30','𓀢','dwꜣ','man with hands raised in front'],
  ['A31','𓀣','Ꜥn','man with hands raised behind him'],
  ['A32','𓀤','ḫbj|hy-hnw|jb','man dancing with arms to the back'],
  ['A33','𓀦','mnjw|ḫwsj|qd|šmꜣw','man with stick and bundle on shoulder'],
  ['A34','𓀧','ḫwsj','man pounding in a mortar'],
  ['A35','𓀨','qd','man building wall'],
  ['A36','𓀩','ꜥftj|nḏ','man kneading into vessel'],
  ['A37','𓀪','ꜥftj','man in vessel'],
  ['A38','𓀫','qjs','man holding necks of two emblematic animals with panther heads'],
  ['A39','𓀬','qjs','man on two giraffes'],
  ['A40','𓀭','.j|nṯr','seated god'],
  ['A41','𓀯','nsw|ḥm|.j','king with uraeus'],
  ['A42','𓀰','nsw|ḥm|.j','king with uraeus and flagellum'],
  ['A43','𓀲','nsw|wsjr','king wearing white crown'],
  ['A44','𓀴','nsw|jtmw','king wearing white crown with flagellum'],
  ['A45','𓀵','bjtj|nsw','king wearing red crown'],
  ['A46','𓀷','bjtj','king wearing red crown with flagellum'],
  ['A47','𓀸','mnjw|sꜣw','shepherd seated and wrapped in mantle, holding stick'],
  ['A48','𓀹','jrj|jrj','beardless man seated and holding knife'],
  ['A49','𓀺','ꜥꜣmw','seated Syrian holding stick'],
  ['A50','𓀻','smr|.j|šps','noble on chair'],
  ['A51','𓀼','špsj|špsj','noble on chair with flagellum'],
  ['A52','𓀽','špsj','noble squatting with flagellum'],
  ['A53','𓀾','twt','standing mummy'],
  ['A54','𓀿','mnj','lying mummy'],
  ['A55','𓁀','sḏr|ẖꜣt','mummy on bed'],
  ['A56','𓁁','','seated man holding stick'],
  ['A57','𓁂','ḥtp-dj-nsw','man holding loaf on mat'],
  ['A58','𓁃','','man applying hoe to ground'],
  ['A59','𓁄','','man threatening with stick'],
  ['A60','𓁅','stj','man sowing seeds'],
  ['A61','𓁆','','man looking over his shoulder'],
  ['A62','𓁇','','Asiatic'],
  ['A63','𓁈','','king on throne holding staff'],
  ['A64','𓁉','','man sitting on heels holding forward cup'],
  ['A65','𓁊','','man wearing tunic with fringes and holding mace'],
  ['A66','𓁋','jḥy|nṯr-Ꜥꜣ','man holding sistrum'],
  ['A67','𓁌','','dwarf'],
  ['A68','𓁍','msdmt','man holding up knife'],
  ['A69','𓁎','','seated man with raised right arm and left arm hanging down'],
  ['A70','𓁏','ḥḥ','seated man with raised arms'],
  ['B1','𓁐','<a href="https://en.wiktionary.org/wiki/zt#Egyptian" class="extiw" title="wikt:zt">zt</a>|<a href="https://en.wiktionary.org/wiki/.j#Egyptian" class="extiw" title="wikt:.j">.j</a>','seated woman'],
  ['B2','𓁑','bkꜣ|jwr','pregnant woman'],
  ['B3','𓁒','msj|jwr','woman giving birth'],
  ['B4','𓁓','msj','combination of woman giving birth and three skins tied together'],
  ['B5','𓁔','rnn|mnꜥt','woman suckling child'],
  ['B6','𓁖','rnn','woman on chair with child on lap'],
  ['B7','𓁗','','queen wearing diadem and holding flower'],
  ['B8','𓁘','','woman holding lotus flower'],
  ['B9','𓁙','','woman holding sistrum'],
  ['C1','𓁚','rꜤ','god with sun-disk and uraeus'],
  ['C2','𓁛','rꜤ','god with falcon head and sun-disk holding ankh'],
  ['C3','𓁟','ḏḥwty','god with ibis head'],
  ['C4','𓁠','ẖnmw','god with ram head'],
  ['C5','𓁡','ẖnmw','god with ram head holding ankh'],
  ['C6','𓁢','jnpw|wp-wꜣwt','god with jackal head'],
  ['C7','𓁣','stḫ|stẖ|stš','god with Seth-animal head'],
  ['C8','𓁤','mnw','ithyphallic god with two plumes, uplifted arm and flagellum'],
  ['C9','𓁥','ḥwt-ḥr','goddess with horned sun-disk'],
  ['C10','𓁦','mꜣꜥt','goddess with feather'],
  ['C11','𓁨','ḥḥ|ḥḥ','god with arms supporting the sky and palm branch on head'],
  ['C12','𓁩','jmn','god with two plumes and scepter'],
  ['C13','𓁪','jmn','C12 reversed'],
  ['C14','𓁫','jmn-ḥr-ḫpš.f','god with two plumes and scimitar'],
  ['C15','𓁬','jmn-ḥr-ḫpš.f','C14 reversed'],
  ['C16','𓁭','jtmw','god wearing red crown with ankh'],
  ['C17','𓁮','mnṯw','god with falcon head and two plumes'],
  ['C18','𓁯','tꜣ-ṯnn','squatting god'],
  ['C19','𓁰','ptḥ|nṯry','mummy-shaped god'],
  ['C20','𓁱','ptḥ|nṯry','mummy-shaped god in shrine'],
  ['C21','𓁲','bs','Bes'],
  ['C22','𓁳','ḫnsw','god with falcon head and moon'],
  ['C23','𓁴','sḫmt|mnḥyt|mḥyt|bꜣstt','goddess with feline head and sun with uraeus'],
  ['C24','𓁵','jtmw','god wearing red crown with scepter'],
  ['D1','𓁶','tp|ḏꜣḏꜣ|ḥꜣ|ḥꜣ|mkḥꜣ','head'],
  ['D2','𓁷','ḥr|ḥr','face'],
  ['D3','𓁸','šnj|jnm|jwn|wš','hair'],
  ['D4','𓁹','jrt|jrj|mꜣꜣ|rs|šp','eye'],
  ['D5','𓁺','jrt|dgi|šp','eye touched up with paint'],
  ['D6','𓁻','jrt|dgi|šp','eye with painted upper lid'],
  ['D7','𓁼','msdmt|ꜥn|ptr|mꜣꜣ','eye with painted lower lid'],
  ['D8','𓁽','ꜥn','eye enclosed in sandy tract'],
  ['D9','𓁿','rmj|rmṯ','eye with flowing tears'],
  ['D10','𓂀','wḏꜣt|jrt|bꜣq|bꜣqt','Eye of Horus'],
  ['D11','𓂁','','left part of the eye of Horus'],
  ['D12','𓂂','jr','pupil'],
  ['D13','𓂃','smd','eyebrow'],
  ['D14','𓂄','','right part of eye of Horus'],
  ['D15','𓂅','','diagonal marking of eye of Horus'],
  ['D16','𓂆','','vertical marking of eye of Horus'],
  ['D17','𓂇','twt','diagonal and vertical markings of eye of Horus'],
  ['D18','𓂈','sḏm|msḏr','ear'],
  ['D19','𓂉','fnḏ|sn|ršw|ḫnt','nose, eye and cheek'],
  ['D20','𓂊','fnḏ|sn|ršw|ḫnt','nose, eye and cheek (cursive)'],
  ['D21','𓂋','r|jw (Ptolemaic) (r[ꜣ]|pẖr)','mouth'],
  ['D22','𓂌','rꜣwj','mouth with two strokes'],
  ['D23','𓂍','ḫmt-rꜣw','mouth with three strokes'],
  ['D24','𓂎','spt','upper lip with teeth'],
  ['D25','𓂏','sptj','lips'],
  ['D26','𓂐','p (Ptolemaic) (psg|bšj|snf)','liquid issuing from lips'],
  ['D27','𓂑','snq|mnḏ|mnꜥt','small breast'],
  ['D28','𓂓','kꜣ','two arms upraised'],
  ['D29','𓂔','kꜣ','combination of hieroglyphs D28 and R12'],
  ['D30','𓂕','nḥb-kꜣw','two arms upraised with tail'],
  ['D31','𓂖','ḥm-kꜣ','arms embracing club'],
  ['D32','𓂘','jnq|ḥpt|sḫn|pgꜣ','arms embracing'],
  ['D33','𓂙','ẖnj','arms rowing'],
  ['D34','𓂚','ꜥḥꜣ','armswith shieldand battle axe'],
  ['D35','𓂜','n|nj (n|nn|jwtj|ḫm|ḫm|smḫ)','arms in gesture of negation'],
  ['D36','𓂝','ꜥ|mḥ','forearm (palm upwards)'],
  ['D37','𓂞','(jmj)|rḏj|ḏj','forearm with bread cone'],
  ['D38','𓂟','mj|m|mwt (mother) (jmj|rḏj|ḏj|ḥnk)','forearm with rounded loaf'],
  ['D39','𓂠','m|mwt (Mother) (ḥnk)','forearm with bowl'],
  ['D40','𓂡','nḫt|ḥwj|ḫꜣj','forearm with stick'],
  ['D41','𓂢','gbꜣ|rmn|jꜣbj|ḥsj|ḥms|grḥ|nj','forearm with palm down and bent upper arm'],
  ['D42','𓂣','mḥ','forearm with palm down and straight upper arm'],
  ['D43','𓂤','ḫwj','forearm with flail'],
  ['D44','𓂥','ḫrp','arm with sekhem scepter'],
  ['D45','𓂦','ḏsr','arm with wand'],
  ['D46','𓂧','d|rarely t (ḏrt)','hand'],
  ['D47','𓂩','ḏrt|sšp|šsp','hand with palm up'],
  ['D48','𓂪','šsp','hand without thumb'],
  ['D49','𓂬','ꜣmm|ḫfꜥ','fist'],
  ['D50','𓂭','ḏbꜥ|ḏbꜥ','one finger'],
  ['D51','𓂷','ꜥnt|ḫꜣj|ṯꜣj|dqr','one finger (horizontal)'],
  ['D52','𓂸','mt (ḥnn|ṯꜣy|ꜥꜣ|kꜣ|bꜣḥ)','phallus'],
  ['D53','𓂺','ḥnn|ṯꜣy|kꜣ|bꜣḥ|wsš','phallus with emission'],
  ['D54','𓂻','nmtt|jw','legs walking'],
  ['D55','𓂽','jw','legs walking backwards'],
  ['D56','𓂾','pd (rd|gḥs|wꜥrt)','leg'],
  ['D57','𓂿','jꜣtj|nkn','leg with knife'],
  ['D58','𓃀','bw','foot'],
  ['D59','𓃁','ꜥb|bꜥ','foot and forearm'],
  ['D60','𓃂','wꜥb','foot under vase from which water flows'],
  ['D61','𓃃','sꜣḥ','three toes oriented leftward'],
  ['D62','𓃄','sꜣḥ','three toes oriented rightward'],
  ['D63','𓃅','sꜣḥ|sꜣḥ','two toes oriented leftward'],
  ['D64','𓃆','','hand with palm down'],
  ['D65','𓃇','ḥnsqty','Sidelock of hair'],
  ['D66','𓃈','spẖr','arm with reed pen'],
  ['D67','𓃉','','one dot'],
  ['E1','𓃒','kꜣ','bull'],
  ['E2','𓃓','kꜣ','bull charging'],
  ['E3','𓃔','bḥs','calf'],
  ['E4','𓃕','ḥsꜣt','sacred cow'],
  ['E5','𓃖','ꜣms','cow suckling calf'],
  ['E6','𓃗','ssmt|jbr','horse'],
  ['E7','𓃘','ꜥꜣ','donkey'],
  ['E8','𓃙','jb','kid'],
  ['E9','𓃛','jw','newborn hartebeest'],
  ['E10','𓃝','bꜣ|ẖnmw','ram'],
  ['E11','𓃞','bꜣ|ẖnmw','ram'],
  ['E12','𓃟','rrj','pig'],
  ['E13','𓃠','mjw|ḫft-ḥr','cat'],
  ['E14','𓃡','ṯsm','dog'],
  ['E15','𓃢','jnpw|ḥrj-sštꜣ','lying canine'],
  ['E16','𓃣','jnpw|ḥrj-sštꜣ','lying canine on shrine'],
  ['E17','𓃥','sꜣb|sꜣb|jw|jꜣbtt','jackal'],
  ['E18','𓃧','wpj-wꜣwt','wolf on standard'],
  ['E19','𓃨','wpj-wꜣwt','wolf on standard with mace'],
  ['E20','𓃩','stẖ|stš|swty','Set-animal'],
  ['E21','𓃫','stẖ|stš|swty|nšnj','lying Set-animal'],
  ['E22','𓃬','mꜣj|šnꜥ','lion'],
  ['E23','𓃭','rw|r|later l (rw|nb)','lying lion'],
  ['E24','𓃮','ꜣby','panther'],
  ['E25','𓃯','db','hippopotamus'],
  ['E26','𓃰','ꜣbw|ꜣb|dnhr','elephant'],
  ['E27','𓃱','mmj|sr|sr','giraffe'],
  ['E28','𓃲','gḥs|mꜣ-ḥḏ','oryx'],
  ['E29','𓃴','gḥs','gazelle'],
  ['E30','𓃵','njꜣw','ibex'],
  ['E31','𓃶','sꜥḥ','goat with collar'],
  ['E32','𓃷','jꜥn|ky|qnd','baboon'],
  ['E33','𓃸','gjf|qnd','monkey'],
  ['E34','𓃹','wn','hare'],
  ['E36','𓃻','ḏḥwty|nswt|nfr|sẖꜣ|sꜣ|ḏd','baboon'],
  ['E37','𓃼','šbt','baboon with receptacle and basket'],
  ['E38','𓃽','kꜣ','long-horned bull'],
  ['F1','𓃾','kꜣ','ox head'],
  ['F2','𓄀','kꜣ','charging ox head'],
  ['F3','𓄁','ꜣt|dp','hippopotamus head'],
  ['F4','𓄂','ḥꜣt','forepart of lion'],
  ['F5','𓄃','šsꜣ','hartebeest head'],
  ['F6','𓄄','šsꜣ','forepart of hartebeest'],
  ['F7','𓄅','šfyt','ram head'],
  ['F8','𓄆','šfyt','forepart of ram'],
  ['F9','𓄇','pḥty|ꜣt','leopardhead'],
  ['F10','𓄈','ḫḫ|ꜥm|ꜥm','head and neck of animal'],
  ['F11','𓄉','ḫḫ|ꜥm|ꜥm','head and neck of animal'],
  ['F12','𓄊','wsr','head and neck of animal'],
  ['F13','𓄋','wp|jp (wpj)','horns'],
  ['F14','𓄍','wp[t]-rnpt','horns with palm branch'],
  ['F15','𓄎','wp[t]-rnpt','horns with palm branch and sun'],
  ['F16','𓄏','ꜥb','horn'],
  ['F17','𓄐','ꜥbw','horn and vase from which water flows'],
  ['F18','𓄑','bḥ|ḥw|ḥ','tusk'],
  ['F19','𓄒','ꜥrt','lower jaw-bone of ox'],
  ['F20','𓄓','ns','tongue'],
  ['F21','𓄔','jdn (msḏr|ḏrḏ|sḏm)','ear of bovine'],
  ['F22','𓄖','pḥt|pḥty','hind-quarters of lion'],
  ['F23','𓄗','ḫpš|ḫpš','forelegof ox'],
  ['F24','𓄘','ḫpš','F23 reversed'],
  ['F25','𓄙','wḥm|wḥm','leg ofox'],
  ['F26','𓄚','ẖn','skin of goat'],
  ['F27','𓄛','dḥr','skin of cow with bent tail'],
  ['F28','𓄜','k (Ptolemaic) (sꜣb)','skin of cow with straight tail'],
  ['F29','𓄝','sṯj','cow\'s skin pierced by arrow'],
  ['F30','𓄞','šdj|šdj','water-skin'],
  ['F31','𓄟','msj','three skins tied together'],
  ['F32','𓄡','ẖt','animal\'s belly'],
  ['F33','𓄢','sd','tail'],
  ['F34','𓄣','jb|ḥ3ty','heart'],
  ['F35','𓄤','nf (Ptolemaic) (nfr)','heart andwindpipe'],
  ['F36','𓄥','smꜣ','lung and windpipe'],
  ['F37','𓄦','šꜥt|jꜣt','backbone and ribs and spinal cord'],
  ['F38','𓄨','psḏ (jꜣt)','backbone and ribs'],
  ['F39','𓄪','jmꜣḫ|psḏ (jmꜣḫ|jmꜣḫ)','backbone and spinal cord'],
  ['F40','𓄫','ꜣw','backbone and spinal cords'],
  ['F41','𓄬','psḏ (šꜥt)','vertebrae'],
  ['F42','𓄭','spr','rib'],
  ['F43','𓄮','spḥt','ribs'],
  ['F44','𓄯','jsw|jwꜥ|swt','bone with meat'],
  ['F45','𓄰','jdt','uterus'],
  ['F46','𓄲','dbn (pẖr|wḏb)','intestine'],
  ['F47','𓄴','dbn (pẖr|wḏb)','intestine'],
  ['F48','𓄶','dbn (pẖr|wḏb)','intestine'],
  ['F49','𓄷','dbn (pẖr|wḏb)','intestine'],
  ['F50','𓄸','spẖr','combination of F46 and S29'],
  ['F51','𓄹','jwf','piece of flesh'],
  ['F52','𓄽','ḥs','excrement'],
  ['F53','𓄾','mt','divine rod with ram head'],
  ['G1','𓄿','ꜣ','Egyptian vulture'],
  ['G2','𓅀','ꜣꜣ','two Egyptian vultures'],
  ['G3','𓅁','mꜣ','combination of Egyptian vulture and sickle'],
  ['G4','𓅂','tjw','buzzard'],
  ['G5','𓅃','ḥrw|nṯr|ḥry|nb','falcon'],
  ['G6','𓅄','bjk|ḥrw|nṯr|nb','combination of falcon and flaggellum'],
  ['G7','𓅆','nṯr|nswt','falcon on standard'],
  ['G8','𓅉','ḥr-nbw/bjk-nbw','falcon on collar of beads'],
  ['G9','𓅊','rꜥ-ḥrw','falcon with sun on head'],
  ['G10','𓅋','skr|ḥnw','falcon in Sokar barque'],
  ['G11','𓅌','spdw|ꜥẖm|ꜥšm|ꜥḫm|gnḥsw|šnbt','image of falcon'],
  ['G12','𓅎','spdw|ꜥẖm|ꜥšm|ꜥḫm|gnḥsw|šnbt','combination of image of falcon and flagellum'],
  ['G13','𓅏','spdw|Horus of <a href="/wiki/Nekhen" class="mw-redirect" title="Nekhen">Nekhen</a> (Hierakonpolis)|ḥrw-nḫnj','image of falcon with two plumes'],
  ['G14','𓅐','mwt|nrt','vulture'],
  ['G15','𓅑','mwt|nrt|mwt','combination of vulture and flagellum'],
  ['G16','𓅒','nbtj','vulture and cobra each on a basket'],
  ['G17','𓅓','m|jm|n (Ptolemaic)','owl'],
  ['G18','𓅔','mm|m|nm','two owls'],
  ['G19','𓅕','m|mj','combination of owl and forearm with conical loaf'],
  ['G20','𓅖','m|mj|mꜥ|ꜥm|m-ꜥ (m-ꜥ)','combination of owl and forearm'],
  ['G21','𓅘','nḥ|nḥḥ','guineafowl'],
  ['G22','𓅙','ḏb','hoopoe'],
  ['G23','𓅚','rḫyt','lapwing'],
  ['G24','𓅛','rḫyt','lapwing with twisted wings'],
  ['G25','𓅜','ꜣḫ','northern bald ibis'],
  ['G26','𓅝','hb|ḏḥwtj','sacred Ibis on standard'],
  ['G27','𓅟','dšr|dšr','flamingo'],
  ['G28','𓅠','gmj','glossy ibis'],
  ['G29','𓅡','bꜣ','saddle-billed stork'],
  ['G30','𓅢','bꜣw','three saddle-billed storks'],
  ['G31','𓅣','bnw','heron'],
  ['G32','𓅤','bꜥḥj','heron on perch'],
  ['G33','𓅥','sdꜣ/sdꜣdꜣ','cattle egret'],
  ['G34','𓅦','njw','ostrich'],
  ['G35','𓅧','ꜥq','cormorant'],
  ['G36','𓅨','mnt|wr','swallow'],
  ['G37','𓅪','bjn|nḏs','sparrow'],
  ['G38','𓅬','ꜣpd|gb|ḥtm','goose'],
  ['G39','𓅭','sꜣ/zꜣ','pintail duck'],
  ['G40','𓅮','pꜣ','pintail flying'],
  ['G41','𓅯','pꜣ|qmꜣ (ḫnj)','pintail alighting'],
  ['G42','𓅰','wšꜣ|ḏfꜣw','widgeon'],
  ['G43','𓅱','w','quail chick'],
  ['G44','𓅳','ww','two quail chicks'],
  ['G45','𓅴','wꜥ|ꜥw','combination of quail chick and forearm'],
  ['G46','𓅶','mꜣw','combination of quail chick and sickle'],
  ['G47','𓅷','ṯꜣ|ṯꜣty','duckling'],
  ['G48','𓅸','sš','three ducklings in nest'],
  ['G49','𓅹','sš','three ducklings in pool'],
  ['G50','𓅺','rḫtj','two plovers'],
  ['G51','𓅻','ḥꜣm/ḥjm','bird pecking at fish'],
  ['G52','𓅼','snm','goose picking up grain'],
  ['G53','𓅽','bꜣ','human-headed bird with bowl with smoke'],
  ['G54','𓅾','wšn|snḏ','plucked bird'],
  ['H1','𓅿','mꜣꜥ|wšm|pq (pꜣq) (ꜣpd|wšn)','head of pintail'],
  ['H2','𓆀','mꜣꜥ|wšm|pq (pꜣq) (ꜣḫ)','head of heron'],
  ['H3','𓆁','pꜣq|pq (ḏd)','head of spoonbill'],
  ['H4','𓆂','nr|rmṯ','head of vulture'],
  ['H5','𓆃','ḏnḥ|pꜣ','wing'],
  ['H6','𓆄','šwt|mꜣꜥt|šw|mꜣꜥ','feather'],
  ['H7','𓆆','ꜥnt','bird foot'],
  ['H8','𓆇','sꜣ/zꜣ','egg'],
  ['I1','𓆈','ꜥšꜣ|ꜥšꜣ','gecko'],
  ['I2','𓆉','št','turtle'],
  ['I3','𓆊','jt|m (msḥ|jt|ḥntj|sbk)','crocodile'],
  ['I4','𓆋','sbk','crocodileon shrine'],
  ['I5','𓆌','sꜣq','crocodile with curved tail'],
  ['I6','𓆎','km','crocodile scales'],
  ['I7','𓆏','ḥqt|ꜥbḫn|qrr|wḥm-ꜥnḫ|ḥfn','frog'],
  ['I8','𓆐','ḥfn','tadpole'],
  ['I9','𓆑','f','horned viper'],
  ['I10','𓆓','ḏt','cobra in repose'],
  ['I11','𓆕','ḏḏ','two cobras'],
  ['I12','𓆗','k (Ptolemaic) (jꜥrt|nbt)','cobra erect as on the forehead of the Pharaoh'],
  ['I13','𓆘','wꜣḏt|nbt','erect cobra on basket'],
  ['I14','𓆙','ḥfꜣw','snake'],
  ['I15','𓆚','ḥfꜣw','snake'],
  ['K1','𓆛','jnt','tilapia'],
  ['K2','𓆜','bw|s (Late period) (bwt)','barbel'],
  ['K3','𓆝','ꜥḏw','mullet'],
  ['K4','𓆞','ẖꜣt|ẖꜣt','elephant-snout fish'],
  ['K5','𓆟','bs (rm)','Petrocephalus bane'],
  ['K6','𓆠','nšmt','fish scale'],
  ['K7','𓆡','špt','puffer'],
  ['K8','𓆢','nꜥr','catfish'],
  ['L1','𓆣','ḫpr|tꜣ','dung beetle'],
  ['L2','𓆤','bjt','bee'],
  ['L3','𓆦','ꜥff','fly'],
  ['L4','𓆧','r (Cryptographic) (znḥm)','locust'],
  ['L5','𓆨','spꜣ','centipede'],
  ['L6','𓆩','ḫꜣ (rarely)','shell'],
  ['L7','𓆫','srqt','scorpion'],
  ['L8','𓆬','',''],
  ['M1','𓆭','m|jmꜣ|jm (jmꜣ|nht|bꜣq|nꜥrt)','tree'],
  ['M2','𓆰','mꜣꜥ-ḫrw','plant'],
  ['M3','𓆱','ḫt|ḫt','branch'],
  ['M4','𓆳','rnpt|rnp|tr','palm branch'],
  ['M5','𓆴','rnpt|tr','combination of palm branch and flat loaf'],
  ['M6','𓆵','tr','combination of palm branch and mouth'],
  ['M7','𓆶','rnp','combination of palm branch and stool'],
  ['M8','𓆷','ꜣḫt|šꜣ','pool with lotus flowers'],
  ['M9','𓆸','sšn|snšn|nḫb|nfr','lotus flower'],
  ['M10','𓆹','nḥbt','lotus bud with straight stem'],
  ['M11','𓆻','wdn|wḏb','flower on long twisted stalk'],
  ['M12','𓆼','ḫꜣ','one lotus plant'],
  ['M13','𓇅','wꜣḏ|mḥw','papyrusstem'],
  ['M14','𓇆','wꜣḏ','combination of papyrus and cobra'],
  ['M15','𓇇','mḥw|ḥꜣ','clump of papyrus with buds'],
  ['M16','𓇉','mḥw|ḥꜣ','clump of papyrus'],
  ['M17','𓇋','j|.j','reed'],
  ['M18','𓇍','jj','combination of reed and legs walking'],
  ['M19','𓇎','ꜥꜣb|ꜥꜣbt','heaped conical cakes between reed and club'],
  ['M20','𓇏','sḫt|sm','field of reeds'],
  ['M21','𓇐','sm','reeds with root'],
  ['M22','𓇑','nḫb|nḫbt','rush'],
  ['M23','𓇓','swt|nswt|šmꜥw|rs|rsj|šmꜥw','sedge'],
  ['M24','𓇔','rs|rsj|rsw','combination of sedge and mouth'],
  ['M25','𓇖','rs|rsj|rsw','combination of flowering sedge and mouth'],
  ['M26','𓇗','šmꜥ|šmꜥw','floweringsedge'],
  ['M27','𓇘','šmꜥ|šmꜥw','combination of flowering sedge and forearm'],
  ['M28','𓇙','mḏw-šmꜥw','combination of flowering sedge and hobble'],
  ['M29','𓇛','nḏm|nḏm','Carob seed-pod'],
  ['M30','𓇜','bnr|bnr','root'],
  ['M31','𓇝','rwḏ','rhizome'],
  ['M32','𓇟','rwḏ','rhizome'],
  ['M33','𓇠','jt','3 grains horizontally'],
  ['M34','𓇣','bdt','ear of emmer'],
  ['M35','𓇤','ꜥḥꜥ|ꜥḥꜥw','stack(of grain)'],
  ['M36','𓇥','ḏr','bundle of flax'],
  ['M37','𓇦','ḏr','bundle of flax'],
  ['M38','𓇧','dmꜣ','wide bundle of flax'],
  ['M39','𓇨','ḏr|dmꜣ','basket of fruit or grain'],
  ['M40','𓇩','js','bundle of reeds'],
  ['M41','𓇫','wꜥn|ꜥš','piece of wood'],
  ['M42','𓇬','wnm|wn','flower'],
  ['M43','𓇭','jrp|kꜣny','vine on trellis'],
  ['M44','𓇮','spd|srt','thorn'],
  ['N1','𓇯','pt|ḥry','sky'],
  ['N2','𓇰','kkw|grḥ','sky with sceptre'],
  ['N3','𓇱','kkw|grḥ','sky with sceptre'],
  ['N4','𓇲','jꜣdt|šnyt','sky with rain'],
  ['N5','𓇳','rꜥ|hrw','sun'],
  ['N6','𓇴','rꜥ|hrw','sun with uraeus'],
  ['N7','𓇵','ẖrt-hrw','combination of sun and butcher\'s block'],
  ['N8','𓇶','psḏ|wbn|sḥḏ|ḥnmmt','sunshine'],
  ['N9','𓇷','pꜣwt|psḏt|psḏntyw','moon with lower half obscured'],
  ['N10','𓇸','pꜣwt|psḏt|psḏntyw','moon with lower section obscured'],
  ['N11','𓇹','jꜥḥ|ꜣbd','crescent moon'],
  ['N12','𓇺','jꜥḥ|ꜣbd','crescent moon'],
  ['N13','𓇻','smdt','combination of crescent moon and star'],
  ['N14','𓇼','sbꜣ|dwꜣ|djw|nṯr','star'],
  ['N15','𓇽','dwꜣt','star in circle'],
  ['N16','𓇾','tꜣ','land with grains'],
  ['N17','𓇿','tꜣ','land'],
  ['N18','𓈀','ꜣḫt|jw|dꜣjw','sandy tract'],
  ['N19','𓈃','ꜣḫty','two sandy tracts'],
  ['N20','𓈄','jdb|wḏb','tongue of land'],
  ['N21','𓈅','jdb|wḏb','short tongue of land'],
  ['N22','𓈆','jdb|wḏb','broad tongue of land'],
  ['N23','𓈇','','irrigation canal'],
  ['N24','𓈈','spꜣt','irrigation canal system'],
  ['N25','𓈉','ḫꜣst','three hills'],
  ['N26','𓈋','ḏw','two hills'],
  ['N27','𓈌','ꜣḫt','sun over mountain'],
  ['N28','𓈍','ḫꜥj','rays of sun over hill'],
  ['N29','𓈎','qꜣꜣ','slope of hill'],
  ['N30','𓈏','jꜣt','mound of earth'],
  ['N31','𓈐','wꜣt|mṯn|ḥr','road with shrubs'],
  ['N32','𓈑','sjn','lump of clay'],
  ['N33','𓈒','','grain'],
  ['N34','𓈔','bjꜣ|ḥmt','ingot of metal'],
  ['N35','𓈖','n|n[j]','ripple of water'],
  ['N36','𓈘','mr|mry','canal'],
  ['N37','𓈙','š|ẖ (Old kingdom) (š)','pool'],
  ['N38','𓈛','š|ẖ (Old kingdom) (š)','deep pool'],
  ['N39','𓈜','š|ẖ (Old kingdom) (š)','pool with water'],
  ['N40','𓈝','šm','poolwith legs'],
  ['N41','𓈞','ḥm|bjꜣ (ḥmt|bjꜣ|ḥmt)','well with ripple of water'],
  ['N42','𓈟','ḥm|bjꜣ (ḥmt|bjꜣ|ḥmt)','well with line of water'],
  ['O1','𓉐','pr','house'],
  ['O2','𓉒','pr-ḥḏ','combination of house and mace with round head'],
  ['O3','𓉓','prt-ḫrw','combination of house, oar, tall loaf and beer jug'],
  ['O4','𓉔','h','shelter'],
  ['O5','𓉕','mrrt','winding wall from upper-left corner'],
  ['O6','𓉗','ḥwt','enclosure'],
  ['O7','𓉞','ḥwt','combination of enclosure and flat loaf'],
  ['O8','𓉟','ḥwt-ꜥꜣt','combination of enclosure, flat loaf and wooden column'],
  ['O9','𓉠','nbt-ḥwt','combination of enclosure, flat loaf and basket'],
  ['O10','𓉡','ḥwt-ḥrw','combination of enclosure and falcon'],
  ['O11','𓉥','ꜥḥ','palace'],
  ['O12','𓉦','ꜥḥ','combination of palace and forearm'],
  ['O13','𓉧','sbḫt|wsḫ|wsḫt','battlemented enclosure'],
  ['O14','𓉨','sbḫt','part of battlemented enclosure'],
  ['O15','𓉩','wsḫt','enclosure with cup and flat loaf'],
  ['O16','𓉪','rwt|tꜣyt','gateway with serpents'],
  ['O17','𓉫','rwt|tꜣyt','open gateway with serpents'],
  ['O18','𓉬','kꜣrj','shrine in profile'],
  ['O19','𓉭','jtrt|pr-wr','shrine with fence'],
  ['O20','𓉯','jtrt|pr-nw','shrine'],
  ['O21','𓉱','sḥ','façade of shrine'],
  ['O22','𓉲','ꜥrq (sḥ|ḥ(ꜣ)b)','booth with pole'],
  ['O23','𓉳','ḥ(ꜣ)b-sd','double platform'],
  ['O24','𓉴','mr','pyramid'],
  ['O25','𓉶','tḫn|mn','obelisk'],
  ['O26','𓉸','ꜥḥꜥw|wḏ','stela'],
  ['O27','𓉹','ḫꜣ','hall of columns'],
  ['O28','𓉺','jwn','column'],
  ['O29','𓉻','ꜥꜣ|ꜥꜣ','horizontal wooden column'],
  ['O30','𓉽','sḫnt','support'],
  ['O31','𓉿','ꜥꜣ','door'],
  ['O32','𓊀','sbꜣ','gateway'],
  ['O33','𓊁','srḫ','façade of palace'],
  ['O34','𓊃','s','door bolt'],
  ['O35','𓊄','sj|sb (sj)','combination of bolt and legs'],
  ['O36','𓊅','jnb','wall'],
  ['O37','𓊊','gsꜣ|sẖnn','falling wall'],
  ['O38','𓊋','qnbt|ꜥrrt','corner of wall'],
  ['O39','𓊌','jnr','stone'],
  ['O40','𓊍','ḫndw','stair single'],
  ['O41','𓊎','jꜥ(r)','double stairway'],
  ['O42','𓊏','šsp|šsp','fence'],
  ['O43','𓊐','šsp|šsp','low fence'],
  ['O44','𓊑','jꜣt','emblem of Min'],
  ['O45','𓊒','jpt','domed building'],
  ['O46','𓊓','jpt','domed building'],
  ['O47','𓊔','nḫn','enclosed mound'],
  ['O48','𓊕','nḫn|sp-snw','enclosed mound'],
  ['O49','𓊖','njwt|p','village'],
  ['O50','𓊗','spt|sp','threshing floor'],
  ['O51','𓊚','šnwt','pile of grain'],
  ['P1','𓊛','dpt|jmw|ꜥhꜥw|ḫdj',''],
  ['P2','𓊝','ḫntj','ship under sail'],
  ['P3','𓊞','ḏꜣj|wiꜣ','sacred barque'],
  ['P4','𓊠','wḥꜥ|wḥꜥ','boat with net'],
  ['P5','𓊡','ṯꜣwt|nfw|ṯꜣw|mḥyt','sail'],
  ['P6','𓊢','ꜥḥꜥ|ꜥḥꜥ','mast'],
  ['P7','𓊣','ꜥḥꜥ|ꜥḥꜥw (ꜥḥꜥ)','combination of mast and forearm'],
  ['P8','𓊤','wsr|ḫrw','oar'],
  ['P9','𓊥','ḫrwfj','combination of oar and horned viper'],
  ['P10','𓊦','ḥmw','rudder'],
  ['P11','𓊧','qd (m(j)njt)','mooringpost'],
  ['Q1','𓊨','st','seatthrone'],
  ['Q2','𓊩','st','carryingchair'],
  ['Q3','𓊪','p|p','stool'],
  ['Q4','𓊫','wrs','headrest'],
  ['Q5','𓊬','hn','chest'],
  ['Q6','𓊭','qrst|qrs','sarcophagus'],
  ['Q7','𓊮','nsr(sr)|tkꜣ|psj|srf|ḫꜣbs','brazier'],
  ['R1','𓊯','ḫꜣwt|wdḥw|ḥtp','high table with offerings'],
  ['R2','𓊰','ḫꜣwt','table with slices of bread'],
  ['R3','𓊲','ḫꜣwt|wdḥw|ḥtp','low table with offerings'],
  ['R4','𓊵','(<a href="/wiki/Hotep" title="Hotep">ḥtp</a>','loaf on mat'],
  ['R5','𓊶','kꜣp','narrow censer'],
  ['R6','𓊷','kꜣp','broad censer'],
  ['R7','𓊸','snṯr|bꜣ','bowl with smoke'],
  ['R8','𓊹','nṯr','Cloth on pole'],
  ['R9','𓊺','bd|nṯry','combination of cloth on pole and bag'],
  ['R10','𓊻','ẖrt-nṯr','combination of cloth on pole, butcher\'s block and slope of hill'],
  ['R11','𓊽','ḏd','reed column'],
  ['R12','𓊾','jꜣt','standard'],
  ['R13','𓊿','jmnty|jmntt','falcon and feather on standard'],
  ['R14','𓋀','jmnty|jmntt|wnmj','Emblem of the West'],
  ['R15','𓋁','jꜣbty|jꜣbtt|jꜣbj','spear, Emblem of the East'],
  ['R16','𓋂','wḫ','sceptre with feathers and string'],
  ['R17','𓋄','tꜣ-wr','wig on pole'],
  ['R18','𓋅','tꜣ-wr','combination of wig on pole and irrigation canal system'],
  ['R19','𓋆','wꜣst|jꜣtt','scepter with feather'],
  ['R20','𓋇','sšꜣt|sẖꜣt','flower with horns'],
  ['R21','𓋈','sšꜣt|sẖꜣt','flower with horns'],
  ['R22','𓋉','mnw|ḫm|ḫm','two narrow belemnites'],
  ['R23','𓋊','mnw|ḫm|ḫm','two broad belemnites'],
  ['R24','𓋋','nt','two bows tied horizontally'],
  ['R25','𓋌','nt','two bows tied vertically'],
  ['R26','𓋍','smꜣ-tꜣwy','combination of land, lung and windpipe, lily, and papyrus'],
  ['R27','𓋎','nt','two arrows crossed over a shield'],
  ['R28','𓋏','bꜣt','Bat'],
  ['R29','𓋐','jtrt|jtrty','niche with serpent'],
  ['S1','𓋑','ḥḏt|wrt|wrrt|nfr|nsyt|nswt|šmꜥw','white crown'],
  ['S2','𓋒','ḥḏt|wrt|wrrt','combination of white crown and basket'],
  ['S3','𓋔','n|jn (dšrt|nt|bjty|mḥw)','red crown'],
  ['S4','𓋕','dšrt|nt|bjty','combination of red crown and basket'],
  ['S5','𓋖','sḫmty|šmꜥw-mḥw|nswt-bjty','Pschent Crown'],
  ['S6','𓋗','sḫmty|nswt-bjty','combination of Pschent Crown and basket'],
  ['S7','𓋙','ḫprš','blue crown'],
  ['S8','𓋚','ꜣtf','Atefcrown'],
  ['S9','𓋛','šwty','shuty-crown (two falcon feathers)]'],
  ['S10','𓋜','mḏḥ','headband'],
  ['S11','𓋝','wsḫ','broad collar'],
  ['S12','𓋞','nbw|nb','collar of beads'],
  ['S13','𓋟','nbw|nb','combination of collar of beads and foot'],
  ['S14','𓋠','ḥḏ','combination of collar of beads and mace with round head'],
  ['S15','𓋣','ṯḥn|ṯḥnt','pectoral'],
  ['S16','𓋤','ṯḥn|ṯḥnt|šsmt',''],
  ['S17','𓋥','ṯḥn|ṯḥnt|šsmt','pectoral'],
  ['S18','𓋧','mnjt','"menatnecklaceandcounterpoise"'],
  ['S19','𓋨','ḫtm|sḏꜣwty','sealwith necklace'],
  ['S20','𓋩','ḫtm|sḏꜣwty','necklace with seal'],
  ['S21','𓋪','jwꜥw','ring'],
  ['S22','𓋫','sṯ|st|tꜣ-wr (stj|šsmtt)','shoulder-knot'],
  ['S23','𓋬','dmḏ','two whipswith shen ring'],
  ['S24','𓋭','ṯs','girdle knot'],
  ['S25','𓋮','ꜣꜥꜥ|jꜥꜣw','garment with ties'],
  ['S26','𓋯','šndyt/šnḏyt','apron'],
  ['S27','𓋲','mnḫt','cloth with two strands'],
  ['S28','𓋳','s (Cryptographic) (ḥbs|ḥꜣy)','cloth with fringe on top and folded cloth'],
  ['S29','𓋴','.s','folded cloth'],
  ['S30','𓋵','sf','combination of folded cloth and horned viper'],
  ['S31','𓋶','smꜣ','combination of folded cloth and sickle'],
  ['S32','𓋷','sjꜣ|sjꜣ','cloth with fringe on the side'],
  ['S33','𓋸','ṯb','sandal'],
  ['S34','𓋹','<a href="/wiki/Ankh" title="Ankh">ꜥnḫ</a>','lifeankh, possibly representing a sandal-strap'],
  ['S35','𓋺','ḫꜣbyt|šwt|sryt','sunshade'],
  ['S36','𓋼','ḫꜣbyt|šwt|sryt','sunshade'],
  ['S37','𓋽','ḫw|ḫwj','fan'],
  ['S38','𓋾','ḥqꜣ|ḥqꜣt','crook'],
  ['S39','𓋿','ꜥwt','shepherd\'s crook'],
  ['S40','𓌀','wꜣs|jꜣtt','wꜣs scepter(uꜣs)'],
  ['S41','𓌁','ḏꜥm','sceptre'],
  ['S42','𓌂','sḫm|ḫrp|ꜥbꜣ','Sekhemscepter'],
  ['S43','𓌃','md(w)|mdw','walking stick'],
  ['S44','𓌄','ꜣms','walking stick with flagellum'],
  ['S45','𓌅','nḫꜣḫꜣ','flagellum'],
  ['S46','𓌆','k (Ptolemaic)','covering for head and neck'],
  ['T1','𓌇','','mace with flat head'],
  ['T2','𓌈','','mace with round head'],
  ['T3','𓌉','','mace with round head'],
  ['T4','𓌋','','mace with strap'],
  ['T5','𓌌','','combination of mace with round head and cobra'],
  ['T6','𓌍','','combination of mace with round head and two cobras'],
  ['T7','𓌎','','axe'],
  ['T8','𓌐','','dagger'],
  ['T9','𓌒','','bow'],
  ['T10','𓌔','','composite bow'],
  ['T11','𓌕','','arrow'],
  ['T12','𓌗','','bowstring'],
  ['T13','𓌘','','joined pieces of wood'],
  ['T14','𓌙','','throw stick vertically'],
  ['T15','𓌚','','throw stick slanted'],
  ['T16','𓌛','','scimitar'],
  ['T17','𓌝','','chariot'],
  ['T18','𓌞','šms','crook with package attached'],
  ['T19','𓌟','','harpoon head'],
  ['T20','𓌠','','harpoon head'],
  ['T21','𓌡','','harpoon'],
  ['T22','𓌢','','arrowhead'],
  ['T23','𓌣','','arrowhead'],
  ['T24','𓌤','','fishingnet'],
  ['T25','𓌥','','float'],
  ['T26','𓌦','','birdtrap'],
  ['T27','𓌧','','trap'],
  ['T28','𓌨','','butcher\'s block'],
  ['T29','𓌩','','butcher\'s block with knife'],
  ['T30','𓌪','','knife'],
  ['T31','𓌫','','knife-sharpener'],
  ['T32','𓌬','','combination of knife-sharpener and legs'],
  ['T33','𓌮','','knife-sharpener of butcher'],
  ['T34','𓌰','','butcher\'s knife'],
  ['T35','𓌱','','butcher\'s knife'],
  ['T36','𓌲','','shield'],
  ['U1','𓌳','','sickle'],
  ['U2','𓌴','','sickle'],
  ['U3','𓌵','',''],
  ['U4','𓌶','','mꜣꜥ'],
  ['U5','𓌷','',''],
  ['U6','𓌸','',''],
  ['U7','𓌻','mr','hoe'],
  ['U8','𓌼','',''],
  ['U9','𓌽','',''],
  ['U10','𓌾','','grain measure (with plural, for grain particles)'],
  ['U11','𓌿','',''],
  ['U12','𓍀','',''],
  ['U13','𓍁','',''],
  ['U14','𓍂','',''],
  ['U15','𓍃','','sled(sledge)'],
  ['U16','𓍄','','sled with jackal head'],
  ['U17','𓍅','','Pick, opening earth'],
  ['U18','𓍆','',''],
  ['U19','𓍇','nw',''],
  ['U20','𓍈','',''],
  ['U21','𓍉','','adze-on-block'],
  ['U22','𓍊','mnḫ','clapper-(of-bell)tool/instrumentforked-staff, etc.'],
  ['U23','𓍋','','chisel'],
  ['U24','𓍍','','handdrill(hieroglyph)'],
  ['U25','𓍎','','version of U24 (hand drill)'],
  ['U26','𓍏','',''],
  ['U27','𓍐','',''],
  ['U28','𓍑','ḏꜣ','fire-drill'],
  ['U29','𓍒','',''],
  ['U30','𓍔','','kiln'],
  ['U31','𓍕','',''],
  ['U32','𓍖','',''],
  ['U33','𓍘','','\'pestle\'-(curved top)'],
  ['U34','𓍙','',''],
  ['U35','𓍚','',''],
  ['U36','𓍛','','fuller\'s-club'],
  ['U37','𓍜','',''],
  ['U38','𓍝','','scale'],
  ['U39','𓍞','',''],
  ['U40','𓍟','wṯswṯs','a support-(to lift)'],
  ['U41','𓍠','','plummet'],
  ['U42','𓍡','','pitchfork'],
  ['V1','𓍢','',''],
  ['V2','𓍬','',''],
  ['V3','𓍮','',''],
  ['V4','𓍯','','lasso'],
  ['V5','𓍰','',''],
  ['V6','𓍱','','rope-(shape)'],
  ['V7','𓍲','','rope-(shape)'],
  ['V8','𓍵','',''],
  ['V9','𓍶','šn','shenring'],
  ['V10','𓍷','','cartouche'],
  ['V11','𓍸','','cartouche-(divided)'],
  ['V12','𓍼','',''],
  ['V13','𓍿','','tethering rope'],
  ['V14','𓎀','',''],
  ['V15','𓎁','jṯj','tethering rope w/ walking legs'],
  ['V16','𓎂','sꜣ','cattlehobble(bil.)'],
  ['V17','𓎃','sꜣ','lifesaver'],
  ['V18','𓎄','',''],
  ['V19','𓎅','',''],
  ['V20','𓎆','','"cattle hobble"'],
  ['V21','𓎓','','Fetter + Cobra'],
  ['V22','𓎔','','whip'],
  ['V23','𓎕','',''],
  ['V24','𓎗','','"command staff" (can also be circular)'],
  ['V25','𓎘','','variant of V24 (can also be circular)'],
  ['V26','𓎙','',''],
  ['V27','𓎚','',''],
  ['V28','𓎛','','a twisted wick'],
  ['V29','𓎝','','(fiber)swab(straw broom)'],
  ['V30','𓎟','','basket(hieroglyph)'],
  ['V31','𓎡','','basket-with-handle(hieroglyph)'],
  ['V32','𓎣','',''],
  ['V33','𓎤','',''],
  ['V34','𓎦','',''],
  ['V35','𓎧','',''],
  ['V36','𓎨','','doubled container(or-added-glyphs)many spellings'],
  ['V37','𓎩','',''],
  ['V38','𓎫','',''],
  ['V39','𓎬','ṯt','?stylized ankh(for Isis)(?)'],
  ['V40','𓎭','',''],
  ['W1','𓎯','','Oil jar'],
  ['W2','𓎰','bꜣs','Oil-jar without ties'],
  ['W3','𓎱','sš','alabasterbasin'],
  ['W4','𓎳','Sṯ','festival chamber, (the tail is also vertical \'Great\': ꜥꜣ)'],
  ['W5','𓎴','',''],
  ['W6','𓎵','','metal vessel'],
  ['W7','𓎶','mꜣṯ','granite bowl'],
  ['W8','𓎷','','deformed granite bowl'],
  ['W9','𓎸','ẖnm','stone jug'],
  ['W10','𓎺','wsḫ|sẖw','cup'],
  ['W11','𓎼','g','ring stand/earthenware pot'],
  ['W12','𓎽','g','flat ring stand'],
  ['W13','𓎾','','earthenware pot'],
  ['W14','𓎿','m|m|gs','water jar'],
  ['W15','𓏁','','water jar with water pouring out'],
  ['W16','𓏂','','water jar with water pouring out and ring stand'],
  ['W17','𓏃','ḫnt','three water jars in rack'],
  ['W18','𓏅','ḫnt','four water jars in rack'],
  ['W19','𓏇','','Milk jug with handle'],
  ['W20','𓏈','','Milk jug with cover'],
  ['W21','𓏉','','Wine jars'],
  ['W22','𓏊','','Beer jug'],
  ['W23','𓏋','','Beer jug with handles'],
  ['W24','𓏌','nuqd--(bil.)-nu','Pot'],
  ['W25','𓏎','','Pot with legs'],
  ['X1','𓏏','','loaf of bread'],
  ['X2','𓏐','',''],
  ['X3','𓏑','',''],
  ['X4','𓏒','','roll of bread'],
  ['X5','𓏕','',''],
  ['X6','𓏖','','loaf with decoration'],
  ['X7','𓏘','','half-loaf of bread'],
  ['X8','𓏙','','cone-shapedbread'],
  ['Y1','𓏛','mḏꜣ-tmḏꜣt','papyrusroll'],
  ['Y2','𓏝','','Papyrus roll-open'],
  ['Y3','𓏞','zẖꜣ; nꜥꜥ','Scribe\'s equipment'],
  ['Y4','𓏟','','Scribe\'s equipment'],
  ['Y5','𓏠','mn','Senet board'],
  ['Y6','𓏡','jbꜣ','game piece'],
  ['Y7','𓏢','bjnt','harp'],
  ['Y8','𓏣','sš|sššt(also sḫm)','Sistrum'],
  ['Z1','𓏤','','Single stroke'],
  ['Z2','𓏥','','Plural stroke (horizontal)'],
  ['Z3','𓏪','','plural strokes (vertical)'],
  ['Z4','𓏭','jwf','Dual stroke'],
  ['Z5','𓏯','','Diagonal stroke (from hieratic)'],
  ['Z6','𓏱','','Substitute for various human figures'],
  ['Z7','𓏲','w (or u)','coil(hieratic equivalent)'],
  ['Z8','𓏳','','Oval'],
  ['Z9','𓏴','swꜣ|sḏ|ḫbs|šbn|wp|wr','Crossed diagonal sticks'],
  ['Z10','𓏵','swꜣ|sḏ|ḫbs|šbn|wp|wr','Crossed diagonal sticks'],
  ['Z11','𓏶','imi','two planks crossed and joined'],
  ['Z12','𓏷','',''],
  ['Z13','𓏸','',''],
  ['Z14','𓏹','',''],
  ['Z15','𓏺','',''],
  ['Z16','𓐄','',''],
  ['Aa1','𓐍','ḫ','Placenta or sieve'],
  ['Aa2','𓐎','','Pustule'],
  ['Aa3','𓐏','','Pustule with liquid issuing from it'],
  ['Aa4','𓐐','bꜣ (rarely)',''],
  ['Aa5','𓐑','ḥp (rarely)','Part of steering gear of a ship'],
  ['Aa6','𓐒','tmꜣ|ṯmꜣ',''],
  ['Aa7','𓐓','','A Smiting-Blade'],
  ['Aa8','𓐖','qn|ḏꜣt|ḏꜣḏꜣt','Irrigation tunnels'],
  ['Aa9','𓐗','',''],
  ['Aa10','𓐘','',''],
  ['Aa11','𓐙','mꜣꜥ and mꜣꜥ in mꜣꜥ-ḫrw',''],
  ['Aa12','𓐚','mꜣꜥ',''],
  ['Aa13','𓐛','m|m|gs',''],
  ['Aa14','𓐜','m|m|gs',''],
  ['Aa15','𓐝','jm|m|gs',''],
  ['Aa16','𓐞','gs',''],
  ['Aa17','𓐟','(sꜣ)',''],
  ['Aa18','𓐠','(sꜣ)',''],
  ['Aa19','𓐡','ḥr',''],
  ['Aa20','𓐢','ꜥpr',''],
  ['Aa21','𓐣','',''],
  ['Aa22','𓐤','',''],
  ['Aa23','𓐥','',''],
  ['Aa24','𓐦','',''],
  ['Aa25','𓐧','',''],
  ['Aa26','𓐨','sbj',''],
  ['Aa27','𓐩','nḏ',''],
  ['Aa28','𓐪','qd',''],
  ['Aa29','𓐫','',''],
  ['Aa30','𓐬','',''],
  ['Aa31','𓐭','',''],
  ['Aa32','𓐮','','']
];
